### ISSUE TITLE
Allow refresh interval to be configured

### ISSUE THREAD

**Issue by jonatino** [pijiulaoshi/ha_philipssomneo#3]
Is it possible to add configuration for refresh interval? Seems to be 60 seconds by default.

**Comment by pijiulaoshi** [comment]
That is definitely possible. I haven't really worked on this project in a while and I am not sure when I will continue again.
I believe I put it in const.py and you might be right about the 60 seconds.

Feel free to work on it yourself if you feel comfortable doing that. If not, I will try to fix it asap, but I can't make any promises as to when I will do this.

**Comment by pijiulaoshi** [comment]
PS: I give it a really quick go and it might work. you can find it in the dev branch.
I haven't tested it. And I must admit that whilst writing this, I realized that my whole code is far from good and should probably not be relied on too much :D maybe it is time for a complete re-write of this component.

**Comment by Jonatino** [comment]
Thank you. It worked perfectly!

**Comment by jonatino** [comment]
The dev branch failed on homeassistant with a bunch of errors. There is no `int` type inside the conf validation, you can't use `self` inside of `Throttle`, and using timedeltas cause homeassistant serialization to fail.

**Comment by pijiulaoshi** [comment]
Thanks for the feedback. I'll try to fix it.

**Comment by pijiulaoshi** [comment]
I think the version in the dev branch is working now. I found a way to do this without Throttle.

Now I hope your idea was to be able to set the minimum time between updates. I don't know if I can force updates with an interval.

Whilst working on your request, I did come to the conclusion that I should probably rewrite the whole thing instead of patching up things in a makeshift way :) I might try a complete rebuild soon. I also hope to add functionallity.

Thanks again for the feedback!
